import {useRouter} from 'next/router'
import {useEffect, useState} from "react"
import { IBand } from 'interfaces/Band'
import type { NextPage } from 'next'
import Head from 'next/head'
import styles from 'styles/Home.module.css'
import PageLayout from 'components/PageLayout'



interface ISingleBandProps {
    band: IBand
}
interface ISingleBandParams {
    params: IBandId
}
interface IBandId {
    id: string
}

const Band: NextPage<ISingleBandProps> = (props) => {
    const {band} = props
    const router=useRouter()
    const [isLoading, setLoading] = useState(false)
    return(
        <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <PageLayout>
        <h2>Pagina de la banda: {band.name}</h2>
        </PageLayout>
      </div>
    )

}

export async function getStaticPaths(){
    const res = await fetch(`http://localhost:3001/bands/`)
    const bands: IBand[] = await res.json()
    return {
        paths: bands.map(band=>{
            return {params: { id: band.id}}
        }),
        fallback: false 
    }
}


export async function getStaticProps({params}: ISingleBandParams ){
    
    const res = await fetch(`http://localhost:3001/bands/${params.id}`)
    const band : IBand = await res.json()  
    return { props: {band}}
}
export default Band