import LoginForm from "../components/LoginForm";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import PageLayout from "components/PageLayout";
import { IUserAuthResponse } from "interfaces/User";
import { useState } from "react";
const Auth = () => {

  const [userData, setUserData] = useState<null | IUserAuthResponse>(null)

  const loginCallback = (data: IUserAuthResponse) => {
    console.log("is logged in", data)
    setUserData(data)
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageLayout userData={userData}>
          <LoginForm loginCallback={(data:IUserAuthResponse) => loginCallback(data)}></LoginForm>
      </PageLayout>
    </div>
  );
};
export default Auth;
